# Generated by Django 6.0.7 on 2026-07-29 05:44

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('color', models.CharField(default='#6c757d', max_length=10, verbose_name='Warna (hex)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nama Tag')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Judul')),
                ('slug', models.SlugField(max_length=320, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Ringkasan')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Isi Artikel')),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/covers/%Y/%m/', verbose_name='Gambar Cover')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Dipublikasikan')], default='draft', max_length=20, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Dipublikasikan pada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Kategori')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
