site_name: Wisnu Blog
theme:
  name: material
  palette:
    primary: indigo
    accent: deep purple
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - content.tabs.link
  code:
    highlight_theme: github-dark
plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      blog_index_template: blog-index.html
      post_template: blog-post.html
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Blog:
      - blog/index.md
extra:
  font:
    text: Ubuntu
    code: Ubuntu Mono
extra_css:
  - stylesheets/custom.css
