site_name: Wisnu Blog
theme:
  language: id
  name: material
  scheme: blue grey
  logo: https://static.vecteezy.com/system/resources/previews/034/845/921/non_2x/artificial-intelligence-ai-logo-icon-vector.jpg
  icon:
    logo: material/library
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.path
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    
  code:
    highlight_theme: github-dark
plugins:
  - search
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      blog_index_template: blog-index.html
      post_template: blog-post.html
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Blog:
      - blog/index.md
extra:
  homepage: https://static.vecteezy.com/system/resources/previews/034/845/921/non_2x/artificial-intelligence-ai-logo-icon-vector.jpg
  font:
    text: Ubuntu
    code: Ubuntu Mono
extra_css:
  - stylesheets/custom.css
extra_javascript:
  - stylesheets/custom.js
