# Generated by Django 6.0.7 on 2026-07-29 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subjek')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('status', models.CharField(choices=[('new', 'Baru'), ('read', 'Dibaca'), ('replied', 'Dibalas'), ('archived', 'Diarsipkan')], default='new', max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim pada')),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('tagline', models.CharField(max_length=200, verbose_name='Tagline / Jabatan')),
                ('bio', models.TextField(verbose_name='Bio Singkat')),
                ('bio_detail', models.TextField(blank=True, verbose_name='Bio Detail')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telepon')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lokasi')),
                ('photo', models.ImageField(blank=True, upload_to='profile/', verbose_name='Foto Profil')),
                ('resume_file', models.FileField(blank=True, upload_to='resume/', verbose_name='File Resume')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profil',
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nama Tag')),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#6c757d', max_length=10, verbose_name='Warna (hex)')),
            ],
            options={
                'verbose_name': 'Tag Proyek',
                'verbose_name_plural': 'Tag Proyek',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('work', 'Pengalaman Kerja'), ('education', 'Pendidikan'), ('certification', 'Sertifikasi'), ('volunteer', 'Volunteer')], default='work', max_length=20, verbose_name='Tipe')),
                ('title', models.CharField(max_length=200, verbose_name='Jabatan / Gelar')),
                ('organization', models.CharField(max_length=200, verbose_name='Perusahaan / Institusi')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lokasi')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('is_current', models.BooleanField(default=False, verbose_name='Masih Berlangsung')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('logo', models.ImageField(blank=True, upload_to='experience/logos/', verbose_name='Logo Organisasi')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='company_profile.profile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Pengalaman',
                'verbose_name_plural': 'Pengalaman',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Proyek')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Klien / Perusahaan')),
                ('short_description', models.CharField(max_length=300, verbose_name='Deskripsi Singkat')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi Lengkap')),
                ('cover_image', models.ImageField(blank=True, upload_to='projects/covers/', verbose_name='Gambar Cover')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Peran dalam Proyek')),
                ('status', models.CharField(choices=[('completed', 'Selesai'), ('ongoing', 'Berlangsung'), ('maintained', 'Dipelihara')], default='completed', max_length=20, verbose_name='Status')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tahun')),
                ('url', models.URLField(blank=True, verbose_name='URL Proyek')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Tampilkan')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='company_profile.profile', verbose_name='Profil')),
                ('tags', models.ManyToManyField(blank=True, to='company_profile.projecttag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Proyek',
                'verbose_name_plural': 'Proyek',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Gambar')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Keterangan')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='company_profile.project', verbose_name='Proyek')),
            ],
            options={
                'verbose_name': 'Gambar Proyek',
                'verbose_name_plural': 'Gambar Proyek',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Skill')),
                ('level', models.PositiveSmallIntegerField(default=80, verbose_name='Level (0-100)')),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skill'), ('language', 'Bahasa'), ('tool', 'Tools & Software')], default='technical', max_length=20, verbose_name='Kategori')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon Class / Emoji')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='company_profile.profile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Keahlian',
                'verbose_name_plural': 'Keahlian',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('website', 'Website'), ('other', 'Lainnya')], max_length=20, verbose_name='Platform')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon_class', models.CharField(blank=True, max_length=100, verbose_name='Icon CSS Class')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Urutan')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Tampilkan')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='company_profile.profile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Link Sosial',
                'verbose_name_plural': 'Link Sosial',
                'ordering': ['order'],
            },
        ),
    ]
