# Generated by Django 6.0.7 on 2026-07-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='company_profile/uploads/profile/', verbose_name='Foto Profil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(blank=True, upload_to='company_profile/uploads/resume/', verbose_name='File Resume'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='company_profile/uploads/covers/', verbose_name='Gambar Cover'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='company_profile/uploads/gallery/', verbose_name='Gambar'),
        ),
    ]
