# Generated by Django 6.0.7 on 2026-07-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nama')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Subjek')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('status', models.CharField(choices=[('new', 'Baru'), ('read', 'Dibaca'), ('replied', 'Dibalas'), ('archived', 'Diarsipkan')], default='new', max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim pada')),
            ],
            options={
                'verbose_name': 'Pesan Kontak Blog',
                'verbose_name_plural': 'Pesan Kontak Blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
