# Generated by Django 6.0.7 on 2026-07-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='Nama Berkas')),
                ('content', models.BinaryField(verbose_name='Konten Berkas')),
                ('content_type', models.CharField(default='application/octet-stream', max_length=100, verbose_name='MIME Type')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Ukuran (Bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'Berkas Media',
                'verbose_name_plural': 'Berkas Media',
                'ordering': ['-created_at'],
            },
        ),
    ]
